### ISSUE TITLE
re-export parsec SourcePos accessors

### ISSUE THREAD

**Issue by frasertweedale** [jgm/commonmark-hs#106]
To deal robustly with source positions of document elements (e.g. for deletion or alteration) we need to be able to drill into the `SourcePos` values in the `SourceRange`.  It is a bit of a nuisance to require a direct dependency on *parsec* to get at the
`sourceLine` and `sourceColumn` functions.  Re-exporting them from *commonmark* would be very helpful!

**Comment by jgm** [comment]
Agreed.

**Comment by jgm** [comment]
Do you feel like making a PR?

**Comment by frasertweedale** [comment]
@jgm yeah I can do it. Will get to it some time in the next week.
