### ISSUE TITLE
Strange parse result on light table with single-char columns

### ISSUE THREAD

**Issue by notriddle** [jgm/commonmark-hs#107]
```markdown
a | b
- | -
1 | 2
```

When I parse the table above using http://pandoc.org/try, and set it to commonmark_x, it writes this out:

> <table>
<thead>
<tr class="header">
<th>a</th>
<th>b</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<p>1 | 2</p>

**Comment by jgm** [comment]
I suspect you're just missing a final newline after the 2

**Comment by jgm** [comment]
I can change trypandoc to add a newline automatically
