### ISSUE TITLE
[fuzz result] backslash at end of fenced code block info string

### ISSUE THREAD

**Issue by notriddle** [jgm/commonmark-hs#115]
Given the following markdown

``````markdown
```\
x
```
``````

commonmark-hs produces this HTML:

```html
<pre><code class="language-x"></code></pre>
```

commonmark.js produces this HTML, and, as near as I can tell, is following the spec:

```html
<pre><code class="language-\">x
</code></pre>
```

**Comment by jgm** [comment]
Yes, that's a bug all right.
