### ISSUE TITLE
Tests fail with "Stack space overflow" on big endian systems

### ISSUE THREAD

**Issue by iliastsi** [jgm/commonmark-hs#129]
Tests for commonmark-0.2.3 fail on big endian systems  (s390x logs [here](https://buildd.debian.org/status/fetch.php?pkg=haskell-commonmark&arch=s390x&ver=0.2.3-1&stamp=1698081571&raw=0), ppc64 logs [here](https://buildd.debian.org/status/fetch.php?pkg=haskell-commonmark&arch=ppc64&ver=0.2.3-1&stamp=1694204652&raw=0)) with:
```
Test suite test-commonmark: RUNNING...
test-commonmark: Stack space overflow: current size 33624 bytes.
test-commonmark: Use `+RTS -Ksize -RTS' to increase it.
Test suite test-commonmark: FAIL
Test suite logged to: dist-ghc/test/commonmark-0.2.3-test-commonmark.log
0 of 1 test suites (0 of 1 test cases) passed.
```

The interesting part is that commonmark sets `-with-rtsopts=-K40K` for tests, but this is not reflected in the error message. This appears to be a GHC bug, see https://gitlab.haskell.org/ghc/ghc/-/issues/10445.

Setting both `-with-rtsopts=-K40K` and `-with-rtsopts=-kc40K` makes the tests pass.

**Comment by jgm** [comment]
Thanks, that's good to know.
