### ISSUE TITLE
Support for GitHub markdown alerts {Note, Important, Tip...}

### ISSUE THREAD

**Issue by pauldesmondparker** [jgm/commonmark-hs#132]
# Problem and Proposed Improvement

## Problem
Github markdown supports **alerts**.
https://github.com/orgs/community/discussions/16925

![image](https://github.com/jgm/pandoc/assets/114397409/5cdfde4e-d23a-4ecf-b55c-6769cf3d3f10)

At present, these do not work with `pandoc`:
```bash
pandoc -f gfm -t html git-flavor.md
```
![image](https://github.com/jgm/pandoc/assets/114397409/f23df547-ec95-42d2-8363-7a8778e2b0bc)

## Proposed Improvement
Add support for these **alerts** under the `gfm` format.

# Alternatives Considered
I have not been able to find any other remediation.

**Comment by jgm** [comment]
In the mean time your best workaround in pandoc would be a Lua filter that matches BlockQuote elements that begin with a Para that begins with `Str "[!NOTE]"`, etc., and replaces this with an Image.
This would be no more than 10 lines of code, I think.

**Comment by jgm** [comment]
Some initial work in issue132 branch

**Comment by jgm** [comment]
Do they have to be uppercase? Let's see:

> [!Tip]
> my tip

> [!warning]
> my warning

**Comment by jgm** [comment]
I guess not.

**Comment by FeralFlora** [comment]
@jgm Is this what it's supposed to look like? 
![image](https://github.com/jgm/commonmark-hs/assets/33608083/01cf16d7-25fc-4479-b031-8f1cef55359f)

This was produced using:
```
pandoc -f commonmark+alerts --metadata title="Alert test" -o "Alert test2.pdf" -t pdf "Alert test2.md"
```

The results were so minimal that I was going to open a bug report, until I tried it with the unsupported `markdown` input format and saw that there was some difference. 

But I don't see the SVG icons mentioned in [the commit](https://github.com/jgm/commonmark-hs/commit/f93cdaf1f13dfb9ae5a315d60a4b72ae9fc3112e). I get the same result using `gfm`, `commonmark+alerts` and `commonmark_x` as input formats, and also whether or not I convert to HTML or PDF.

**Comment by jgm** [comment]
Yes, I decided to go with the minimal version rather than including the SVG.
This gives you the structure you need -- you can decide yourself how to style the alerts, add images (with a filter), or whatever.

I do have code for the SVGs GitHub uses, but in the end this seemed too opinionated.

I also wanted to make sure these alerts would translate well to other formats that support admonitions, e.g. rst, asciidoc, docbook.

**Comment by FeralFlora** [comment]
> Yes, I decided to go with the minimal version rather than including the SVG. This gives you the structure you need -- you can decide yourself how to style the alerts, add images (with a filter), or whatever.
> 
> I do have code for the SVGs GitHub uses, but in the end this seemed too opinionated.
> 
> I also wanted to make sure these alerts would translate well to other formats that support admonitions, e.g. rst, asciidoc, docbook.

Okay, thanks for the clarification.

**Comment by FeralFlora** [comment]
@jgm Any chance the `alerts` extension will be applied to the standard markdown format too? As is, you have to decide between `mark` and `list_without_preceding_blanklines` and `alerts`, since `gfm` and `commonmark` don't support the former two, but `markdown` doesn't support the latter.

**Comment by jgm** [comment]
You could open an issue requesting this.

**Comment by radcool** [comment]
> You could open an issue requesting this.

@jgm, has anyone followed up and opened an issue on this, as you suggested? If not, I'd like to open one as I for one would like Pandoc markdown to support this extension.

Should I open the issue under [jgm/commonmark-hs](https://github.com/jgm/commonmark-hs) or [jgm/pandoc](https://github.com/jgm/pandoc)?

**Comment by jgm** [comment]
If it's for pandoc's `markdown` format, then in jgm/pandoc

**Comment by radcool** [comment]
https://github.com/jgm/pandoc/issues/9716 opened.
