### ISSUE TITLE
[fuzz result] inline processing instructions can't parse more than once in a block?

### ISSUE THREAD

**Issue by notriddle** [jgm/commonmark-hs#139]
There's something wrong with the way this sample is parsed.

```markdown
this works wrong <?xml?> <?xml?>

this works fine <xml> <xml>
```

[pandoc try](<https://pandoc.org/try/?params=%7B%22text%22%3A%22this+works+wrong+%3C%3Fxml%3F%3E+%3C%3Fxml%3F%3E%5Cn%5Cnthis+works+fine+%3Cxml%3E+%3Cxml%3E%5Cn%22%2C%22to%22%3A%22html5%22%2C%22from%22%3A%22commonmark%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D>)

The second paragraph has two tags, but the first, for some reason, does not:

```html
<p>this works wrong <?xml?> &lt;?xml?&gt;</p>
```

commonmark.js does what I'd expect, turning both processing instructions into inline HTML tags. [The spec](https://spec.commonmark.org/0.30/#raw-html) also doesn't seem to say anything that would make processing instructions different than tags.

<details>

Events from pulldown-cmark:

```rust
"} <??><??>\n" -> [
  Start(Paragraph)
    Text(Borrowed("} "))
    InlineHtml(Borrowed("<??>"))
    InlineHtml(Borrowed("<??>"))
  End(Paragraph)
]
```

Events from pandoc:

```rust
"} <??><??>\n" -> [
  Start(Paragraph)
    Text(Boxed("} "))
    InlineHtml(Boxed("<??>"))
    Text(Boxed("<??>"))
  End(Paragraph)
]
```

Events from commonmark.js:

```rust
"} <??><??>\n" -> [
  Start(Paragraph)
    Text(Boxed("} "))
    InlineHtml(Boxed("<??>"))
    InlineHtml(Boxed("<??>"))
  End(Paragraph)
]
```

</details>

**Comment by jgm** [comment]
This is undoubtedly because of the scannedForProcessingInstruction stuff in https://github.com/jgm/commonmark-hs/blob/master/commonmark/src/Commonmark/Tag.hs#L160-L177
I think that was added to avoid some pathological parsing cases, but I can't see how the code was ever supposed to work!  Similar code for declarations.  Probably both should be removed, but I need to remember why they were added.

**Comment by jgm** [comment]
Oh, I see -- this is nonbacktracking state. Well, then it should be easily fixed.
