### ISSUE TITLE
Quadratic output size explosion with tables extension

### ISSUE THREAD

**Issue by notriddle** [jgm/commonmark-hs#145]
Same issue as https://github.com/raphlinus/pulldown-cmark/issues/832 (though, due to subtle differences in the pipe_tables extension, commonmark-hs requires three bytes per line instead of two).

The problem is, because the table extension fills in missing table cells, you can force the output to grow as the square of the input by adding one column and one row. This is a side-effect of the extension as specified, and follows from the geometric definition of "squaring": the size of the output is proportional to the *area* of a square, but the input is proportional to the *parameter*.

```console
$ python -c 'N=100; print("x|" * N + "\n" + "-|" * N + "\n" + "x|\n" * N)' | commonmark --extension=pipe_tables | wc -c
102362
$ python -c 'N=1000; print("x|" * N + "\n" + "-|" * N + "\n" + "x|\n" * N)' | commonmark --extension=pipe_tables | wc -c
10023062
$ python -c 'N=10000; print("x|" * N + "\n" + "-|" * N + "\n" + "x|\n" * N)' | commonmark --extension=pipe_tables | wc -c
1000230062
```

The output size grows roughly as square of the input size: factor of 10 growth on input means factor of 100 growth on output.

cmark-gfm avoids this problem by putting a limit on the number of cells it will "autocomplete." md4c simply limits the number of columns.

**Comment by jgm** [comment]
What sort of limit to the number of columns would be safe?

**Comment by mity** [comment]
> What sort of limit to the number of columns would be safe?

There's ofc no definite answer to that. MD4C currently limits tables to have no more than 128 columns but I'm not overly happy with that: 128 is about as small as one can go in order not to be too restrictive for genuine use cases on one hand and on the other hand it still allows a malicious input where almost every two bytes on input translate to more than 1000 bytes of output (`128 * strlen("<td></td>")`), killing any (imho natural) assumption that the output size is always roughly proportional to the input.

I'm considering to abandon the column count limitation altogether and switch to something what would target more directly the ratio of input/output sizes. Perhaps something similar to this pseudo code:

```
if(col_count * row_count > 1000  &&
   raw_input_table_byte_count < col_count * row_count / 20)
{
   // Big table requesting to auto-generate 80+ % of empty cells?
   // No way: Downgrade the block in question to an ordinary paragraph.
}
```

**Comment by digitalmoksha** [comment]
`comrak` does the same as `cmark-gfm`, limiting the number of auto-completed cells to 500,000

**Comment by mity** [comment]
@digitalmoksha I assume it's a limit per document rather than per table, right?

**Comment by digitalmoksha** [comment]
Actually it looks like it's per table

https://github.com/kivikakk/comrak/blob/main/src/parser/table.rs#L352-L366
