### ISSUE TITLE
[fuzz result] backslashing `&` entities doesn't escape them in link destinations

### ISSUE THREAD

**Issue by notriddle** [jgm/commonmark-hs#149]
Consider this markdown:

```markdown
[link](\&#33;)
```

The important part is the `\&#33;` part, which [the reference implementation translates to `&amp;#33;`](https://spec.commonmark.org/dingus/?text=%5Blink%5D(%5C%26%2333%3B)), but [commonmark-hs](https://pandoc.org/try/?params=%7B%22text%22%3A%22%5Blink%5D%28%5C%5C%26%2333%3B%29%22%2C%22to%22%3A%22html5%22%2C%22from%22%3A%22commonmark%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D) translates to `!`, seemingly ignoring the backslash.

<details>

Events from pulldown-cmark:

```rust
"[](*\\&#4;)\n" -> [
  Start(Paragraph)
    Start(Link { link_type: Inline, dest_url: Boxed("%2A%26%234%3B"), title: Borrowed(""), id: Borrowed("") })
    End(Link)
  End(Paragraph)
]
```

Events from pandoc:

```rust
"[](*\\&#4;)\n" -> [
  Start(Paragraph)
    Start(Link { link_type: Inline, dest_url: Boxed("%2A%04"), title: Inlined(InlineStr { inner: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], len: 0 }), id: Borrowed("") })
    End(Link)
  End(Paragraph)
]
```

Events from commonmark.js:

```rust
"[](*\\&#4;)\n" -> [
  Start(Paragraph)
    Start(Link { link_type: Inline, dest_url: Boxed("%2A%26%234%3B"), title: Inlined(InlineStr { inner: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], len: 0 }), id: Borrowed("") })
    End(Link)
  End(Paragraph)
]
```

AST from [pandoc](https://pandoc.org/try/?params=%7B%22text%22%3A%22%5B%5D%28%2A%5C%5C%26%234%3B%29%5Cn%22%2C%22to%22%3A%22json%22%2C%22from%22%3A%22commonmark%22%7D):

```text
Pandoc {
    meta: {},
    blocks: [
        Para(
            [
                Link(
                    (
                        Attr(
                            "",
                            [],
                            [],
                        ),
                        [],
                        Target(
                            "*\u{4}",
                            "",
                        ),
                    ),
                ),
            ],
        ),
    ],
}
```

**Comment by jgm** [comment]
Instead of doing
```hs
target <- unEntity <$> pLinkDestination
```
in pInlineLink, we need to handle the entities as part of pLinkDestination.
