### ISSUE TITLE
Challenges Outputting Context-Dependent Things To Text

### ISSUE THREAD

**Issue by IsaacTheKind** [jgm/commonmark-hs#155]
I need to make an `IsBlock` instance for `Text` so that i can output text for search purposes. However certain parts of the instances like `paragraph` and `list` need to be rendered differently based on context. For instance, most paragraphs should end with `"\n\n"`, except the last paragraph which should just end with `"\n"`. Or in the case of lists, different amounts of spaces need to be prepended based on the nesting level. When outputting HTML this is a non-issue because we can output something like `<ul><li><\li></ul>` and the nesting will be worked out by the HTML renderer. So we don't need to change the way Commonmark outputs based on the nesting level. The same general reasoning applies to paragraphs. It seems to me that `IsBlock` isn't flexible enough to deal with rendering to text because I need to know things like the nesting level in order to properly render a nested list, or I need to know if a paragraph is at the end of a document to properly render a paragraph. Am I just confused or is there not really a way to render the text as I need?

**Comment by jgm** [comment]
First, for API hygiene reasons, I wouldn't create an instance for Text.  Instead, create your own special type (which in the limiting case could just be a newtype wrapping a Text). After all, there are lots of ways to convert commonmark to something textual.

Once you take that step, I think you'll see that there are many ways to solve your problem.  One way would be to have your newtype wrap something like `Doc Text` from my doclayout package; this is explicitly designed for laying out textual documents that need indentation, spaces between paragraphs but not at the end, and so on.  Granted, this isn't a Text, but it can be converted to one in one step using the `render` function.  Using doclayout will also take care of text wrapping to a fixed width, if that's something you desire, and tabular layouts.

**Comment by IsaacTheKind** [comment]
Thank you, I was able to achieve what I wanted using this approach.
