### ISSUE TITLE
Not an issue ;-)

### ISSUE THREAD

**Issue by matze-dd** [jgm/commonmark-hs#27]
Hi,
correct tracking of source positions is a great undertaking, especially when it comes to integration with proofreading software. *Much lesser* attempts for LaTeX and Markdown can be seen in
[TeXtidote](https://github.com/sylvainhalle/textidote) and [Tex2txt](https://github.com/matze-dd/Tex2txt).

Many thanks already for pandoc, and good progress with this project!
Matthias

**Comment by jgm** [comment]
thanks
