### ISSUE TITLE
rawHtmlSpec gets in the way of parsing special links

### ISSUE THREAD

**Issue by srid** [jgm/commonmark-hs#42]
In [neuron](https://github.com/srid/neuron) we support special links of the format `<a34sfef4>` (as well as: `<z:zettels?tag=foo>`) that has to be processed by the app to be replaced with some custom HTML stuff. 

I wrote a syntax spec defining the parser in `syntaxInlineParsers`, but when actually using it it was only getting applied for `<1hello>` but not `<hello>` (which gets rendered as raw HTML). 

`rawhtmlspec` in `defaultBlockSpecs` is the cause of this behaviour. What is the recommended way to turn this behaviour off, so that applications have the flexibility to parse syntax with angle brackets?

**Comment by jgm** [comment]
You want to disable parsing of block-level HTML entirely?  You can simply define your own variant of `defaultBlockSpecs` that leaves out the block HTML parser.
``` haskell
myDefaultBlockSpecs :: (Monad m, IsBlock il bl) => [BlockSpec m il bl]
myDefaultBlockSpecs =
    [ indentedCodeSpec
    , fencedCodeSpec
    , blockQuoteSpec
    , atxHeadingSpec
    , setextHeadingSpec
    , thematicBreakSpec
    , listItemSpec (bulletListMarker <|> orderedListMarker)
    -- , rawHtmlSpec  -- <- leave this out!
    , attributeSpec
    ]
```

If you want to parse raw HTML blocks, but just not ones that begin with `<a34s...>` or whatever, then you can modify the block HTML parser.

**Comment by srid** [comment]
Thanks.

> If you want to parse raw HTML blocks, but just not ones that begin with <a34s...> or whatever, then you can modify the block HTML parser.

I suppose this is what I will end up doing. Though it would be nice if there is someway to override the angle-bracket link content parsing without modifying the library.

**Comment by jgm** [comment]
You don't actually have to modify the library.  You can create your own `myBlockHtmlSpec` that just modifies the standard one a bit (this would only be a few lines of code, I think, because you can use the standard one in the definition), and use this in a custom `myDefaultBlockSpecs` as above.

**Comment by srid** [comment]
> because you can use the standard one in the definition

Hmm, you mean I can reuse the `rawHtmlSpec` function? I don't see how though, because it doesn't take any arguments. Actually I'm at the point of forking this function and disabling that `ty == 7` case altogether ...

**Comment by jgm** [comment]
See my comment on your PR.
