### ISSUE TITLE
Unable to set attributes on table

### ISSUE THREAD

**Issue by srid** [jgm/commonmark-hs#47]
When I add an attribute like `{.overflows .collapsing .compact .sortable}` immediately above the table, in the AST I get a wrapping `div` (with these attributes), which wrapes the `table` element. I'd expect these attributes to be applied to the `<table>` tag itself.

**Comment by jgm** [comment]
Until recently Table didn't have a place for attributes. That is changed in the dev version of pandoc-types, so we can fix that.
