### ISSUE TITLE
One of the extensions seems to use FFI 

### ISSUE THREAD

**Issue by srid** [jgm/commonmark-hs#50]
I saw this in GHCJS for a particular markdown content. It doesn't happen with bare commonmark parser, but only when the extensions are enabled. I'll get to debugging and isolating the problem one of the following days, but it would be great if someone already knew what it could be off the top of their head ...

![image](https://user-images.githubusercontent.com/3998/83363564-608cfc00-a368-11ea-80e2-60351d13bf51.png)

**Comment by srid** [comment]
[Extensions enabled](https://github.com/srid/neuron/blob/ff15bab56877d38164813d2c953f6f9c94014d0a/neuron/src/lib/Neuron/Markdown.hs#L101-L119) for this repro.

**Comment by jgm** [comment]
I'm pretty sure this doesn't come from commonmark-hs.
Look at the build-depends for commonmark-extensions:
```
     base >=4.7 && <5
    , text
    , bytestring
    , containers
    , transformers
    , parsec
    , commonmark >= 0.1 && < 0.2
```

**Comment by srid** [comment]
You are right. The errors comes only when syntax highlighting is used (via fenced code blocks with language identifier). Looks like it is coming from the skylighting library.

Looking at its deps, I see that it depends on stuff like `ansi-terminal` ... I wonder how I can provide syntax highlighting on GHCJS ...

**Comment by jgm** [comment]
The thing you have to worry about is not ansi-terminal (that's pure Haskell I believe), but pcre-regex-builtin (which uses FFI on the C library libpcre).
Unfortunately I know of no pure Haskell regex library that has the features we need to emulate the regex processor KDE uses.

**Comment by jgm** [comment]
If you're targeting js, you could always just use a js syntax highlighting library!

**Comment by jgm** [comment]
Note: I've pushed changes to skylighting that use a pure Haskell regex implementation instead of depending on libpcre.
I'll release this soon.

**Comment by srid** [comment]
Awesome! That means I can use that in http://www.cerveau.app/ to re-enable syntax highlighting.
