### ISSUE TITLE
Release to hackage?

### ISSUE THREAD

**Issue by maralorn** [jgm/commonmark-hs#51]
Hello! Thanks for commonmark!

The newest version of https://github.com/srid/neuron, uses the commonmark library (quite successfully I, as mainly a user, might add). To bring the new features to all users (and e.g. nixpkgs) we would like to make a new neuron release. Sadly releasing to hackage with a dependency not on hackage is a bad idea.
So for this situation it would be marvelous if we could make a first commonmark release to hackage soon.

@jgm Would you be willing to do that?

If you don‘t want to maintain commonmark on hackage, @srid has offered to do the hackage maintenance, if you were to agree with that.

**Comment by jgm** [comment]
I've been meaning to do this soon, yes!  Got a big backlog of other things, but I'll try to get to it before long.  I'm glad the library has been working well for you.

**Comment by jgm** [comment]
It's released!
