### ISSUE TITLE
Build failures with GHC-7.8..GHC-8.0

### ISSUE THREAD

**Issue by phadej** [jgm/commonmark-hs#53]
The `base >=4.7` dependency and other metadata allowed picking install-plans for GHC-7.8, 7.10 and 8.0.

7.8 and 7.10 simply don't work, as package uses `StrictData` extension. That is fixed by adding

```cabal
other-extensions: StrictData
```

to `commonmark.cabal`.

GHC-8.0 fails to build package due `{-# SCC tokenize #-}` and `{-# SCC untokenize #-}` pragmas in `Tokens` module. According to https://downloads.haskell.org/~ghc/8.2.1/docs/html/users_guide/8.2.1-notes.html (and empricaally), this is GHC-8.2+ feature

> SCC annotations can now be used for declarations.

This can be fixed by either `base >= 4.10` lower-bound (exclude GHC-8.0 using `base` as a proxy), by removing `SCC` pragmas, or adding CPP around them.

---

I made a revision adding `other-extensions` and bumping `base >=4.10` lower bound. https://hackage.haskell.org/package/commonmark-0.1.0.0/revisions/

**Comment by jgm** [comment]
I was thinking we could just support 8.2+.  I mean, even debian stable has 8.4.  Is there really any need to support 8.0x?  So I guess I'm inclined towards raising the base lower bound, unless someone gives me a good reason to support 8.0.x.

**Comment by jgm** [comment]
(I suppose that if haddock wanted to use this to add markdown support, *that* could be a reason to support as many ghc versions as possible.)

**Comment by jgm** [comment]
I'll see if I can make the changes to support the older versions.

**Comment by jgm** [comment]
I've made commits that support ghc 8.0+ and adjusted base versions accordingly.

**Comment by phadej** [comment]
You may drop

```
  if !impl(ghc >= 8.0)
    build-depends: semigroups == 0.18.*
```

from cabal files too.

**Comment by jgm** [comment]
I'll do that, thanks for the suggestion.
