### ISSUE TITLE
test/task_lists.md missing in commonmark-extensions.cabal extra-source-files

### ISSUE THREAD

**Issue by maralorn** [jgm/commonmark-hs#55]
The title says it all. As first witness I call the nixpkgs test failure:

https://hydra.nixos.org/build/124359086/nixlog/1

```
Linking dist/build/test-commonmark-extensions/test-commonmark-extensions ...
running tests
Running 1 test suites...
Test suite test-commonmark-extensions: RUNNING...
test-commonmark-extensions: test/task_lists.md: openFile: does not exist (No such file or directory)
Test suite test-commonmark-extensions: FAIL
Test suite logged to:
dist/test/commonmark-extensions-0.2.0.0-test-commonmark-extensions.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for '/nix/store/30prf3a1lcvs3wvs2jb2bc5pc4rfd6c0-commonmark-extensions-0.2.0.0.drv' failed with exit code 1
```

**Comment by jgm** [comment]
Thanks.  Do you know of any easy automatic way to test building from the package tarball (besides using nix)?  I know I can use sdist and then unpack and cd etc., but it seems to me this should be built into stack or cabal somehow.

**Comment by maralorn** [comment]
Not that I am aware of. Sorry.

**Comment by maralorn** [comment]
I have just been told that haskell-ci runs the tests on the packed tarball. So that would work.
