### ISSUE TITLE
Consider Megaparsec

### ISSUE THREAD

**Issue by lierdakil** [jgm/commonmark-hs#6]
A quick question. Perhaps this repo is a good place to try using Megaparsec instead of Parsec?

Megaparsec has some niceties compared to Parsec, which include better error reporting and Unicode support, and it's also reportedly faster. The only downside I can think of (apart from switching parsers being potentially a lot of work) is that Megaparsec is not as stable in terms of API and features -- but that comes with territory with an actively-maintained package.

Since this repo is not (yet) directly tied to Pandoc, I thought that this might be a good place for such experiments.

Just a thought, no pressure.

**Comment by jgm** [comment]
I've thought about that, but I've made it a priority for the core commonmark library to have as few dependencies as possible, so that e.g. it could be included in haddock. (cf. https://github.com/haskell/haddock/issues/794.)  megaparsec would introduce quite a lot of new transitive dependencies.
