### ISSUE TITLE
Abstraction difficulty and help requested

### ISSUE THREAD

**Issue by jtdaugherty** [jgm/commonmark-hs#62]
Thanks for this library!

I'm attempting to migrate the [matterhorn](https://github.com/matterhorn-chat/matterhorn) project from `cheapskate` to `commonmark`. I'm running into a challenge with the API and I'd like some advice.

The challenge I'm facing roughly revolves around the fact that `commonmark` requires that both the block type and inline type both instance `Monoid` and `Semigroup`. Concretely, this means that:

* My block type must be capable of representing an empty block sequence, an individual block, and an entire document (block sequence), and
* My inline type must be capable of representing an empty inline value, an individual inline element, and an entire sequence of inline elements.

To me, this leads to some awkward data type design in my application and some awkward situations where my AST needs to be tested for pathological cases I hope to never encounter. For example, my AST permits representing things like paragraphs with nothing in them if I have something like `data MyBlock = Para MyInline | ...` and `data MyInline = EmptyInline | ...`. I'd rather just not allow that at all, and not even support the presence of a paragraph unless it has something in it. Encoding the absence of inlines, the presence of a single inline, or the presence of a sequence (tree) of inlines all in the same type makes the type cumbersome to pattern-match on in many places I need to use it.

When I first started trying to use this package, the API I think I expected was to provide `commonmark` with sequences of inlines (to build blocks) and sequences of blocks (to build documents). In other words, I expected
```
class IsBlock il b where
    paragraph :: [il] -> b
```
(Or some other sequence type.)

Looking at the source for `commonmark`, I can see how the current design probably worked well for the `Html` type you provide, but the AST types I want to make are far less homogenized.

Thoughts?

(Attn @kquick)

**Comment by jgm** [comment]
Perhaps it would help to see how we handle this in pandoc. We have `Inlines` and `Blocks` types that are basically newtype wrappers around `Seq Inline` and `Seq Block`.  These are instances of Monoid.  You could do the same sort of thing for your types, presumably.
For the definitions, see Text.Pandoc.Builder.

**Comment by jgm** [comment]
Having a look at commonmark-pandoc might also help.

**Comment by jtdaugherty** [comment]
@jgm Thanks! I took a look at the source for those packages and that does help to see how you've approached things. While it looks like you're taking the approach I was essentially trying to avoid, it does show that it's feasible. I'm reworking our types to be more compatible with this approach, so I'll close this since I think I'm able to make enough progress now.
