### ISSUE TITLE
Nested blocks in footnotes are rendered in reverse order

### ISSUE THREAD

**Issue by hagl** [jgm/commonmark-hs#63]
Lists in footnotes are rendered in the wrong order. For example
```
Footnote containing a list [^list]

[^list]:
    1. First item
    1. Second item
```
will be rendered as
![image](https://user-images.githubusercontent.com/1162118/97804878-d6b4c800-1c52-11eb-8eb2-8f587729a357.png)

This is because the blocks nested in a footnote will be stored in `referenceMap` instead of `nodeStack` and will therefore won't be reversed correctly by `reverseSubforests`

See also https://github.com/srid/neuron/issues/350

**Comment by jgm** [comment]
Oh, that's a bad one! Thanks for reporting.
