### ISSUE TITLE
Autolink extension seems to gobble up additional content

### ISSUE THREAD

**Issue by jtdaugherty** [jgm/commonmark-hs#65]
With `commonmark-extensions` version 0.2.0.2, I am encountering a problem where the `autolinkSpec` causes an issue with the following input:
```
[a link](http://www.google.com/)stuff
```
In my tests, the `stuff` portion is not represented in the final parsed structure. Here's a test case using my own types.

First, the case that works as expected where I just use the default syntax spec:
```
> commonmark "-" "[broken](https://commonmark.org/)stuff" :: Either ParseError Blocks
Right (Blocks (fromList [Para (Inlines (fromList [EHyperlink (URL "https://commonmark.org/") (Inlines (fromList [EText "broken"])),EText "stuff"]))]))
```
Then the case where I use `autolinkSpec <> defaultSyntaxSpec` (notice that the `stuff` text node is missing):
```
> parseMarkdown Nothing "[broken](https://commonmark.org/)stuff"
Blocks (fromList [Para (Inlines (fromList [EHyperlink (URL "https://commonmark.org/") (Inlines (fromList [EText "broken"]))]))])
```

CC @kquick

**Comment by jgm** [comment]
I suspect it's only going to work if you put `autolinkSpec` after `defaultSyntaxSpec` (rather than before).  If you put it before, then the autolink gets recognized before the regular link.

**Comment by jgm** [comment]
Anyway, try that -- but it seems that something may still be broken.

**Comment by jtdaugherty** [comment]
That does resolve the issue I'm seeing but then autolinking doesn't seem to work:
```
> parseMarkdown Nothing "[broken](https://commonmark.org/)stuff http://www.google.com/"
Blocks (fromList [Para (Inlines (fromList [EHyperlink (URL "https://commonmark.org/") (Inlines (fromList [EText "broken"])),EText "stuff",ESpace,EText "http",EText ":",EText "/",EText "/",EText "www",EText ".",EText "google",EText ".",EText "com",EText "/"]))])
```

**Comment by jtdaugherty** [comment]
Thinking about this a bit more, I guess I had assumed that this extension would know to only match links that didn't already come embedded in Markdown link syntax. I think I also saw somewhere in your documentation that these extensions generally need to come before the default syntax spec, which works well for all the other extensions I've tried (as well as the two that I've written in my own project).

**Comment by jgm** [comment]
OK, this needs more thought.

Inline parsing goes in two phases: first, we parse "chunks" which might be brackets or emphasis delimiters, regular words, or things like inline code.  Then there's a complex process to match delimiters and recognize links and emphasis and images.

Currently the autolinks extension is implemented at the first, "chunk" parsing level, which is why it is interfering with regular links, I guess.  But at that level we don't yet know what belongs to a regular link.

**Comment by jgm** [comment]
I'll need to look at the code and try to figure out why that content is being dropped.

**Comment by jgm** [comment]
I think that this is what's going on:

- In the "chunks" parsing phase, this gets recognized as a URL and autolinked:  `http://www.google.com/)stuff`

- Then, in the regular link recognition phase, recognize a potential link with `[a link]` and try to parse a link suffix.  This means untokenizing the following chunk (the autolink) and parsing the parenthesized bit.  We probably just need to check for a remainder and reinsert it as plain text.  Or, maybe we should forbid unbalanced parens in an autolink.

**Comment by jtdaugherty** [comment]
Here's another data point for how this extension behaves:
```
https://www.cis.upenn.edu/~bcpierce/papers/dblenses-tr.pdf
```
leads to `https://www.cis.upenn.edu/` being linked and `~bcpierce/papers/dblenses-tr.pdf` being left behind.

**Comment by jgm** [comment]
Here's the list of raw tokens before parsing for the link suffix in the original example:
``` haskell
[Tok {tokType = Symbol '(', tokPos = (line 1, column 9), tokContents = "("},Tok {tokType = WordChars, tokPos = (line 1, column 10), tokContents = "http"},Tok {tokType = Symbol ':', tokPos = (line 1, column 14), tokContents = ":"},Tok {tokType = Symbol '/', tokPos = (line 1, column 15), tokContents = "/"},Tok {tokType = Symbol '/', tokPos = (line 1, column 16), tokContents = "/"},Tok {tokType = WordChars, tokPos = (line 1, column 17), tokContents = "www"},Tok {tokType = Symbol '.', tokPos = (line 1, column 20), tokContents = "."},Tok {tokType = WordChars, tokPos = (line 1, column 21), tokContents = "google"},Tok {tokType = Symbol '.', tokPos = (line 1, column 27), tokContents = "."},Tok {tokType = WordChars, tokPos = (line 1, column 28), tokContents = "com"},Tok {tokType = Symbol '/', tokPos = (line 1, column 31), tokContents = "/"},Tok {tokType = Symbol ')', tokPos = (line 1, column 32), tokContents = ")"},Tok {tokType = WordChars, tokPos = (line 1, column 33), tokContents = "stuff"}]
```

**Comment by jtdaugherty** [comment]
Thank you so much, @jgm!

**Comment by jtdaugherty** [comment]
I'd love to find out when this goes out to Hackage. Is there some way I could get notified?

**Comment by jgm** [comment]
I've already put out a new release.

**Comment by jtdaugherty** [comment]
Thank you!
