### ISSUE TITLE
Autolink bug in 0.2.0.3

### ISSUE THREAD

**Issue by jtdaugherty** [jgm/commonmark-hs#66]
Here's the test case:
```
[broken2](http://www.google.com/)does this work?
```
Result: `does this work` is lost, only `?` appears in the parsed result.

Another failing case:
```
[broken2](http://www.google.com/)does this work.
```

**Comment by jgm** [comment]
I think I see the problem.

**Comment by jgm** [comment]
OK, new versions of commonmark and commonmark-extensions released.

**Comment by jtdaugherty** [comment]
I can confirm that this resolved the issue for me. Thank you!
