### ISSUE TITLE
Hyperlinks with leading or trailing whitespace unsupported

### ISSUE THREAD

**Issue by jtdaugherty** [jgm/commonmark-hs#67]
I'm not sure if this is just due to a strict interpretation of a spec somewhere, but I recently found that `commonmark-hs` will not autolink these cases:
```
[test ](http://www.google.com/)
[ test](http://www.google.com/)
```

**Comment by jgm** [comment]
My hunch is that commonmark-hs is paying attention to the fact that the `]` in the first example is not right-flanking.  But that shouldn't matter; the spec for links doesn't require it to be right-flanking. (And cmark parses this as a link.)

**Comment by jgm** [comment]
OK, not hard to fix.

**Comment by jtdaugherty** [comment]
Thank you!
