### ISSUE TITLE
Unsure how to accomplish this... maybe worth documenting?

### ISSUE THREAD

**Issue by hyperrealgopher** [jgm/commonmark-hs#68]
More of a documentation/clarification question, I think. I'm having a bit of an implementation problem.

I'm parsing from Markdown to fancy ascii-art-oriented text files.

i want to parse Markdown files so that the headers (levels 1 through 6, or whatever) are transformed into neat ascii art. I do this using a custom ASCII art font file format (it's really basic). I want the user to be able to add their own fonts eventually and also read some configuration from file in the future so users can specify which font heading level 1 uses, which font heading level 2 uses, etc. 

Here's an example of a parser that takes markdown and parses to a text file, specifically the heading parser bit: https://github.com/hyperrealgopher/burrow/blob/master/src/Markdown/ToTextFile.hs#L80

Or here's my more complicated part for generating "gopher protocol menus:" https://github.com/hyperrealgopher/burrow/blob/master/src/Markdown/ToGopherMenu.hs

Here's where the parsing starts for the above: https://github.com/hyperrealgopher/burrow/blob/master/src/Build.hs#L128

As for my own research/reading I've concluded to the best of my ability that this is relevant, but I'm not sure exactly how it can help me: 

`commonmarkwith`
https://hackage.haskell.org/package/commonmark-0.1.1/docs/Commonmark-Parser.html#v:commonmarkWith
> Like commonmark, but allows specifying a custom syntax and a monadic context (since some syntax extensions may only be defined in certain monads, e.g. an extension for include files may require IO).

My goal is to be able to load the font files once and pass it to the parser.

I think in my head I came up with one bad solution where I use `IO GopherFile` as a type, and then every time a heading is encountered, it reads the font file from disk, but that seems really inefficient and frankly, kind of annoying to make everything `IO GopherFile`. I am new to Haskell, so maybe I'm mistaken and also maybe I'm making a very basic error.

Thank you for your time.

**Comment by jgm** [comment]
Instead of using `IO` you could try using a `State` monad.  The font file could be passed along in state.  Then you'd only have to read it once. Something like
``` haskell
newtype WithGopherFont a =
        WithGopherFont { unWithGopherFont :: State GopherFont a }
```
Once you've parsed your commonmark into this structure, you'll get a state monad and you just need to run it with the gopher font as state parameter.

**Comment by jgm** [comment]
Alternatively you could define the typeclass instances for a function
```
GopherFont -> a
```
and then simply apply the function you get from the parser to the font to get your value.
The state monad approach does essentially the same thing but with some convenient plumbing.

**Comment by hyperrealgopher** [comment]
I appreciate you taking the time to explain in detail, for a Haskell beginner like myself. Thank you.

I was talking with someone else, their suggestion was to just have something that would parse the AST generated, but we decided to go to something related to your `State` suggestion: `Reader` (as seen in [my Burrow project](https://github.com/hyperrealgopher/burrow). I think this leaves room to update it to a record syntax in case i want to pass more things to the parser in the future, too (like a `data Environment = Environment { fonts :: AsciiFonts, bulletStyles :: BulletMap }`).

**Comment by jgm** [comment]
Reader is better than State for this, agreed!
