### ISSUE TITLE
Add wikilinks extension

### ISSUE THREAD

**Issue by jgm** [jgm/commonmark-hs#69]
See `wikilinks` branch.

**Comment by jgm** [comment]
If we want formatting in the title part, we probably need to modify pBracketedSuffix again so that a list of Chunks rather than Toks gets passed to it.  A list of Chunks can be downshifted to a list of Toks, but it also allows you to extract e.g. all the parsed content that occurs before a Chunk with a single `|` token.  The problem with this is that a Chunk is currently an internal data structure; Chunks would have to be promoted to the public API.  Alternatively, instead of a chunk, we could use something like a `[(a, [Tok])]`.

**Comment by srid** [comment]
```
[[title|https://example.org]]
```

Shouldn't this be reversed? Zettelkaten apps like Obsidian and Foam put the link inline text on the right side. https://github.com/srid/neuron/issues/373#issuecomment-688438177

**Comment by jgm** [comment]
This is how it's done in GitHub wikis.  I don't know why everyone has to reinvent the wheel in incompatible ways!

**Comment by jgm** [comment]
Now in `master` branch.

**Comment by jgm** [comment]
The way I've currently implemented this, the title part can have commonmark formatting (e.g. italics) -- that does not work on GitHub, but it seems like something that could be useful.

If this weren't needed -- if both sides were treated as plain uninterpreted text -- then I suppose we could have a `wikilink :: Text -> Text -> inline` type, and then you'd just need a typeclass that interprets the parameters differently to get these different styles.  But I don't know if I really want to give up the formatted titles.

**Comment by jgm** [comment]
More prior art for the "link alias" or description (what I've called "title" above) occuring before the page name:

https://bobswift.atlassian.net/wiki/spaces/MARKDOWN/pages/42631183/How+to+use+WikiLinks

Prior art for the link alias coming second:

https://github.com/jsepia/markdown-it-wikilinks/blob/master/test/fixtures/wikilinks.txt

Argh!

**Comment by srid** [comment]
For the record, I decided to fork this extension for two reasons -- (a) and (b) stated below. I believe (a) can be achieved in the commonmark-hs extension somehow (as a configuration option), but (b) is neuron-specific and you probably don't want it in the library .. hence the fork.

```haskell
-- | Like `Commonmark.Extensions.Wikilinks.wikilinksSpec` but Zettelkasten-friendly.
--
-- Compared with the official extension, this has two differences:
--
-- - (a) Supports flipped inner text (default and only option), eg: `[[Foo | some inner text]]`
-- - (b) Supports neuron folgezettel, i.e.: #[[Foo]] or [[Foo]]#
wikilinksSpec ::
  (Monad m, CM.IsInline il, HasWikilinks il) =>
  CM.SyntaxSpec m il bl
wikilinksSpec =
  mempty
    { CM.syntaxInlineParsers =
        [ P.try $
            P.choice
              [ P.try (CT.symbol '#' *> pWikilink WikiLinkTag),
                P.try (pWikilink WikiLinkBranch <* CT.symbol '#'),
                P.try (pWikilink WikiLinkNormal)
              ]
        ]
    }
  where
    pWikilink typ = do
      replicateM_ 2 $ CT.symbol '['
      P.notFollowedBy (CT.symbol '[')
      url <-
        CM.untokenize
          <$> many
            ( CT.satisfyTok
                ( \t ->
                    not (CT.hasType (CM.Symbol '|') t || CT.hasType (CM.Symbol ']') t)
                )
            )
      title <-
        M.option url $
          CM.untokenize
            <$> ( CT.symbol '|'
                    *> many (CT.satisfyTok (not . CT.hasType (CM.Symbol ']')))
                )
      replicateM_ 2 $ CT.symbol ']'
      return $ wikilink typ url (CM.str title)

data WikiLinkType
  = -- | [[Foo]]
    WikiLinkNormal
  | -- | [[Foo]]#
    WikiLinkBranch
  | -- | #[[Foo]]
    WikiLinkTag
  deriving (Eq, Show)

class HasWikilinks il where
  wikilink :: WikiLinkType -> Text -> il -> il

instance CM.Rangeable (CM.Html a) => HasWikilinks (CM.Html a) where
  wikilink typ url il =
    -- Store `typ` in link title, for later lookup.
    CM.link url (show typ) il

instance
  (HasWikilinks il, Semigroup il, Monoid il) =>
  HasWikilinks (CM.WithSourceMap il)
  where
  wikilink typ url il = (wikilink typ url <$> il) <* CM.addName "wikilink"

instance HasWikilinks (CP.Cm b B.Inlines) where
  wikilink typ t il = CP.Cm $ B.link t (show typ) $ CP.unCm il

```
