### ISSUE TITLE
Build failure with GHC 9.0.1

### ISSUE THREAD

**Issue by sjakobi** [jgm/commonmark-hs#72]
```
src/Commonmark/Inlines.hs:333:10: error:
    A pragma is not allowed in this position: {-# SCC attrParser #-}
    |
333 |          {-# SCC attrParser #-} (AddAttributes <$> attrParser)
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Commonmark/Inlines.hs:337:7: error:
    A pragma is not allowed in this position: {-# SCC pDelimChunk #-}
    |
337 |   <|> {-# SCC pDelimChunk #-} pDelimChunk specmap isDelimChar
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I can't find anything about a relevant parser change in GHC's [release notes](http://downloads.haskell.org/~ghc/latest/docs/html/users_guide/9.0.1-notes.html) or the [migration guide](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0), so I'm wondering whether this could be a regression.

**Comment by sjakobi** [comment]
> I can't find anything about a relevant parser change in GHC's [release notes](http://downloads.haskell.org/~ghc/latest/docs/html/users_guide/9.0.1-notes.html) or the [migration guide](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0), so I'm wondering whether this could be a regression.

I've reported the issue in https://gitlab.haskell.org/ghc/ghc/-/issues/19325.

**Comment by int-index** [comment]
Moving the parenthesis should fix it

```diff
-  {-# SCC attrParser #-} (AddAttributes <$> attrParser)
+ ({-# SCC attrParser #-}  AddAttributes <$> attrParser)
```

**Comment by sjakobi** [comment]
Thanks for the hint and for updating the migration guide, @int-index! :)
