### ISSUE TITLE
Hard line-breaks aren't handled correctly

### ISSUE THREAD

**Issue by agrafix** [jgm/commonmark-hs#74]
Thank you for this awesome library!

I'm getting unexpected results when rendering markdown with hard line-breaks:

Example input:
```
This is a test for how newlines \
are handled.

\

**Testing** \ 
More \
Okay
```

Output:
```
<p>This is a test for how newlines <br />
are handled.</p>
<p>\</p>
<p><strong>Testing</strong> \
More <br />
Okay</p>
```

Expected Output:
```
<p>This is a test for how newlines <br />
are handled.</p>
<br />
<p><strong>Testing</strong> <br />
More <br />
Okay</p>
```

**Comment by jgm** [comment]
Note: In the terminology of the commonmark spec, these are hard line breaks.

But this behavior accords with the spec, which says:

> Hard line breaks are for separating inline content within a block. Neither syntax for hard line breaks works at the end of a paragraph or other block element:

**Comment by agrafix** [comment]
Got it -- thanks for the quick reply! It seems like the free standing `\` confuses the parser and that's why the sub-sequent use of it doesn't work anymore in

```
**Testing** \ 
More \
Okay
```

**Comment by jgm** [comment]
Ah, okay, there were two issues here and I only noticed the first (which is not a bug, the `\` in a paragraph by itself).

The second issue (the `\` after `** `)  does look like a bug.

**Comment by jgm** [comment]
Wait -- you have a space right after the `\` on the line with `**Testing**`. So it doesn't count as a backslash immediately before a newline.  Not a bug after all.  Expected behavior.
