### ISSUE TITLE
How does `Commondmark.Pandoc` differ from `Text.Pandoc.Readers.CommonMark`

### ISSUE THREAD

**Issue by tysonzero** [jgm/commonmark-hs#8]
More of a question than an issue, but yeah it seems like Pandoc already knows how to convert commonmark into a Pandoc AST?

**Comment by jgm** [comment]
That module uses cmark-gfm, which wraps a C library.
This is a pure Haskell implementation.  It will also
support extensions (including the usual pandoc
markdown extensions), unlike the current pandoc
CommonMark reader, which only supports a few
limited ones.
