### ISSUE TITLE
Pandoc hangs when using +sourcepos on markdown files ending with ordered or unordered lists

### ISSUE THREAD

**Issue by jmjjg** [jgm/commonmark-hs#80]
# Problem

### a.md

```markdown
# a

- one
- two

```

### b.md

```markdown
# b

```

## Command used

```bash
pandoc --from commonmark+sourcepos --to native *.md
```

## Explanations

The command above hangs.

- if I remove `+sourcepos` from the command, it works well
- if I add a blank line and a dot at the end of `a.md` last line, it works well
- if I use no list at the end of the file in `a.md`, it works well

# Environment

- pandoc 2.14.2
- Ubuntu 18.04.5 LTS

**Comment by jgm** [comment]
Result of `--tokenize`:
```
[Tok {tokType = Symbol '-', tokPos = "a.md" (line 1, column 1), tokContents = "-"},Tok {tokType = Spaces, tokPos = "a.md" (line 1, column 2), tokContents = " "},Tok {tokType = WordChars, tokPos = "a.md" (line 1, column 3), tokContents = "a"},Tok {tokType = LineEnd, tokPos = "a.md" (line 1, column 4), tokContents = "\n"},Tok {tokType = WordChars, tokPos = "b.md" (line 1, column 1), tokContents = "b"},Tok {tokType = LineEnd, tokPos = "b.md" (line 1, column 2), tokContents = "\n"}]
```

**Comment by jgm** [comment]
With my example, adding blank lines to the end of a.md or beginning of b.md makes no difference; it still hangs.
