### ISSUE TITLE
`fenced_divs` doesn't support unbraced class names in commonmark

### ISSUE THREAD

**Issue by not-my-profile** [jgm/commonmark-hs#84]
**Explain the problem.**
```
$ printf ':::test\n:::' | pandoc -f markdown+fenced_divs
<div class="test">

</div>
$ printf ':::test\n:::' | pandoc -f commonmark+fenced_divs
<p>:::test :::</p>
```

**Pandoc version?**
pandoc 2.16.2 on Linux

**Comment by not-my-profile** [comment]
Thanks :) I didn't know about this repository. Maybe it's worth pinning an issue at the pandoc repository pointing out related repositories? Something like:

* for issues about commonmark see [commonmark-hs](https://github.com/jgm/commonmark-hs/issues)
* for issues about the syntax highlighting see [skylighting](https://github.com/jgm/skylighting)
* etc.

**Comment by jgm** [comment]
It's pretty easy for me to move them around...

**Comment by not-my-profile** [comment]
Right ... it's just that I like to avoid creating duplicate issues.

It might also be worth highlighting some smaller dependencies since they might be more approachable for contributors.

I think it's a shame that GitHub doesn't let you show "related repositories" in the sidebar or something like that.
