### ISSUE TITLE
Implement `markdown_in_html_blocks` extension

### ISSUE THREAD

**Issue by not-my-profile** [jgm/commonmark-hs#85]
As in pandoc: https://pandoc.org/MANUAL.html#extension-markdown_in_html_blocks

**Comment by jgm** [comment]
Commonmark has its own built in way of including markdown in HTML blocks, so this is not needed (or desired---it's a mess to handle arbitrary markdown in HTML blocks).

**Comment by not-my-profile** [comment]
Ah thanks, I didn't know that. I tried:

```
<figure>
*test*
</figure>
```

apparently with CommonMark you need a newline after the start tag. The following works as expected:

```
<figure>

*test*
</figure>
```
