### ISSUE TITLE
Too-wide version bounds in commonmark-extensions

### ISSUE THREAD

**Issue by david-christiansen** [jgm/commonmark-hs#93]
I just tried building a new Hakyll project, and got the following error from `commonmark-extensions`:
```
src/Commonmark/Extensions/FancyList.hs:32:17: error:
    Variable not in scope:
      getParentListType
        :: ParsecT [Tok] (BPState m il bl) m (Maybe ListType)
   |
32 |   mbListType <- getParentListType
   |                 ^^^^^^^^^^^^^^^^^
```

The issue seems to be that `commonmark-extensions` version `0.2.3.1` specifies a lower bound of `0.2` for `commonmark`, but `Commonmark.Blocks` in that package didn't export `getParentListType` until version `0.2.2`.

**Comment by chris-martin** [comment]
Would you mind making a metadata revision to the 0.2.3.1, please?

**Comment by jgm** [comment]
The issue is fixed in 0.2.3.3, is it not?

**Comment by chris-martin** [comment]
It is, but it is still important to correct version bounds on *all* releases of a package, not just the latest. If you have an old release with incorrectly lenient bounds, then the constraint solver just ends up deciding to use that one, and people's builds fail.

**Comment by jgm** [comment]
ok, done

**Comment by chris-martin** [comment]
Thank you :heart:
