### ISSUE TITLE
Attributes extension regression in commonmark-extensions 0.2.3.3

### ISSUE THREAD

**Issue by srid** [jgm/commonmark-hs#99]
Upstream issue: https://github.com/EmaApps/emanote/issues/372

## Repro

The particular trigger seems to be the `{.timeline}` part in [the source](https://raw.githubusercontent.com/EmaApps/emanote/master/docs/guide/query.md):
 
<img width="257" alt="image" src="https://user-images.githubusercontent.com/3998/201493040-7b22bdd5-25e7-489d-ae00-f3d7b24a4ab5.png">

This renders as:

![image](https://user-images.githubusercontent.com/3998/201495565-6f25aa8d-14c5-45f9-9f45-9c69cb38d7ca.png)

## 0.2.3.3

Once I go back to `commonmark-extensions` version `0.2.3.2` this problem goes away, thus suggesting that the culprit must be in the only change here: https://github.com/jgm/commonmark-hs/commit/db528aa7b90edf4de84630f149cdc0dcbe396555 (done for #96).

**Comment by jgm** [comment]
I just compiled the latest source and ran the commonmark executable on
````
## Timeline queries

Queries can be rendered as a timeline by using the `timeline` code block attribute.

~~~markdown
```query {.timeline}
tag:blog/ema
```
~~~
````
Result was
````

````
<h2>Timeline queries</h2>
<p>Queries can be rendered as a timeline by using the <code>timeline</code> code block attribute.</p>
<pre><code class="language-markdown">```query {.timeline}
tag:blog/ema
```
</code></pre>
````

which looks right.  So I haven't been able to reproduce this.

**Comment by srid** [comment]
It could be the extension *order* that is triggering it? I'll try to find come up with a minimal independent repro.

**Comment by kukimik** [comment]
This was fixed by https://github.com/jgm/commonmark-hs/commit/2ae8919eff0155481c47c16edfc70130d306ad0f.

**Comment by jgm** [comment]
Good to know, will close now.
